#version 460 core

layout(local_size_x = 8, local_size_y = 8) in;

layout(binding = 0) uniform sampler2D vx_read_tex;
layout(binding = 1) uniform sampler2D vy_read_tex;
layout(binding = 3) uniform sampler2D smoke_read_tex;

layout(binding = 0, r32f) writeonly uniform image2D vx_write_temp_image;
layout(binding = 1, r32f) writeonly uniform image2D vy_write_temp_image;
layout(binding = 3, rgba16f) writeonly uniform image2D smoke_write_temp_image;

layout(binding = 4, r32f) uniform image2D pressure_map;
layout(binding = 5, rgba16f) uniform image2D solid_map;
layout(binding = 6, r32f) uniform image2D vorticity;

layout(std140, binding = 1) uniform constants {
    ivec4 grid_size;
    vec4 wind;
    float time_step;
    float density;
    float t_ambient;
    float t_weight_coeff;
    float t_temp_coeff;
    float vorticity_confinement;
    float _pad0;
    float _pad1;
    float cell_size;
};

uniform int wind_tunnel;

void main() {
    ivec2 idx = ivec2(gl_GlobalInvocationID.xy);

    if(idx.x >= grid_size.x || idx.y >= grid_size.y) return;

    bool should_be_solid_x = idx.x == 0 || idx.x == (grid_size.x - 1);
    bool should_be_solid_y = idx.y == 0 || idx.y == (grid_size.y - 1);

    bool should_be_solid = wind_tunnel == 1 ? should_be_solid_y : should_be_solid_x || should_be_solid_y;

    if(should_be_solid) {
        imageStore(solid_map, idx, vec4(0, 0, 0, 1));
    }

}